/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  AppRecipe as AppRecipe
} from './components/app-recipe/app-recipe';

declare global {
  interface HTMLAppRecipeElement extends AppRecipe, HTMLElement {
  }
  var HTMLAppRecipeElement: {
    prototype: HTMLAppRecipeElement;
    new (): HTMLAppRecipeElement;
  };
  interface HTMLElementTagNameMap {
    "app-recipe": HTMLAppRecipeElement;
  }
  interface ElementTagNameMap {
    "app-recipe": HTMLAppRecipeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-recipe": JSXElements.AppRecipeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRecipeAttributes extends HTMLAttributes {
      match?: any;
    }
  }
}

